"""empty message

Revision ID: 6efd523a0007
Revises: 
Create Date: 2025-03-18 14:26:43.129406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6efd523a0007'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('exam_seat_number', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['enrollment_number'])
        batch_op.create_unique_constraint(None, ['exam_seat_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('exam_seat_number')
        batch_op.drop_column('enrollment_number')

    # ### end Alembic commands ###
